version: '3.8'

services:
  appdev:
    image: golang:latest
    working_dir: /app
    volumes:
      - .:/app
    command: go mod tidy &&  top -c
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"


networks:
  app-network:
    driver: overlay
    attachable: true
    name: app_network
    # external: true
